@startuml
skinparam groupInheritance 4

package models {
    class Administrator extends User
    enum Category
    class DNI
    class Guest extends User
    enum League
    abstract class List<T>
    class Match
    class MatchList extends List
    interface Participant
    class ParticipantList extends List
    class Player extends User implements Participant
    enum Role
    enum Sport
    class Statistics
    class Team implements Participant
    class TimeFrame <<(R,yellow)>>
    class Tournament
    class TournamentInfo <<(R,yellow)>>
    class TournamentList extends List
    class User
    class UserList extends List

    User --> Role
    Player --> Statistics
    Player --> DNI
    Team "0..1" o--> "1..*" Participant
    Match *--> ParticipantList
    Tournament *--> MatchList
    Statistics "1" ..> "0..*" Category
    Tournament *--> ParticipantList
    Tournament --> TimeFrame
    Tournament --> TournamentInfo
    TournamentInfo --> Category
    TournamentInfo --> League
    TournamentInfo --> Sport
    TournamentList "1" o--> "0..*" Tournament
    ParticipantList "1" o--> "0..*" Participant
    MatchList "1" o--> "0..*" Match
    UserList "1" o--> "0..*" User
}

package service {
    class AuthenticationService implements Authenticator
    interface Authenticator
    enum ErrorType
    interface ParticipantManager
    class ParticipantService implements ParticipantManager
    interface TournamentManager
    class TournamentService implements TournamentManager

    AuthenticationService --> User
    ParticipantService *--> List
    ParticipantService <-- AuthenticationService
    TournamentService <-- AuthenticationService
    TournamentService *--> List
}

package views {
    class CLI
    class ErrorView
    class TournamentView

    package commands {
        abstract class Command
        class CommandFactory
        class CommandArguments
        CommandFactory --> Command
        Command .right.> CommandArguments
        Command <|-- SubCommandA
        Command <|-- SubCommandB
        Command <|-- SubCommandC
        SubCommandA .right.> AuthenticationService
        SubCommandB .down.> ParticipantService
        SubCommandC .left.> TournamentService
    }

    CLI --> CommandFactory
    CLI ..> Command
}

package utils {
    enum CommandFeedback
    class Console
    class DefaultEmailValidator implements EmailValidator
    interface DomainPolicy
    class EmailAdress
    interface EmailValidator
    class RestrictedEmail extends EmailAdress
    class UpmDomainPolicy implements DomainPolicy
    class UpmEmail extends RestrictedEmail
}

class SportsManager

SportsManager --> CLI
@enduml