package es.upm.etsisi.service;

public enum Error {
    DUPLICATE_ELEMENT_ERROR,
    DUPLICATE_TOURNAMENT_ERROR,
    DUPLICATE_MATCH_ERROR,
    PLAYER_ALREADY_IN_MATCH_ERROR,
    ELEMENT_NOT_FOUND,
    NAME_FORMAT_ERROR,
    PLAYER_NOT_IN_TEAM,
    USER_NOT_FOUND,
    PLAYER_NOT_FOUND,
    TEAM_NOT_FOUND,
    TOURNAMENT_NOT_FOUND,
    WRONG_PASSWORD,
    PLAYER_IN_GAME_ERROR,
    TEAM_IN_GAME_ERROR,
    PLAYER_ALREADY_IN_TEAM_ERROR,
    INVALID_COMMAND,
}
