package es.upm.etsisi.service;

public enum Error {
    DUPLICATE_ELEMENT_ERROR,
    DUPLICATE_TOURNAMENT_ERROR,
    DUPLICATE_MATCH_ERROR,
    PLAYER_ALREADY_IN_MATCH_ERROR,
    ELEMENT_NOT_FOUND,
    NAME_FORMAT_ERROR,
    PLAYER_NOT_IN_TEAM,
    INVALID_COMMAND,
}
